name: Build
on:
  push:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: svelte-kit sync
        run: |
          npm ci
          npx svelte-kit sync
      - name: lint and build
        run: |
          npx nx format --base master --check
          npx svelte-check --tsconfig ./tsconfig.json
          npx nx lint
          npx nx test
          npx nx build
